[package]
name = "bg-radar-linux"
version = "0.1.0"
edition = "2024"

[dependencies]
encoding_rs = "0.8.35"
libc = "0.2.174"
rust-utils = { git = "https://github.com/SoxPopuli/rust-utils.git", tag = "v1.8.0", features = [
    "byte_readers"
]}
static_assertions = "1.1.0"
