use crate::int_enum;

int_enum! {
    pub enum Class: u8 {
        Mage = 1,
        Fighter = 2,
        Cleric = 3,
        Thief = 4,
        Bard = 5,
        Paladin = 6,
        FighterMage = 7,
        FighterCleric = 8,
        FighterThief = 9,
        FighterMageThief = 10,
        Druid = 11,
        Ranger = 12,
        MageThief = 13,
        ClericMage = 14,
        ClericThief = 15,
        FighterDruid = 16,
        FighterMageCleric = 17,
        ClericRanger = 18,
        Sorcerer = 19,
        Monk = 20,
        Shaman = 21,
        Ankheg = 101,
        Basilisk = 102,
        BasiliskGreater = 103,
        BearBlack = 104,
        BearBrown = 105,
        BearCave = 106,
        BearPolar = 107,
        Carrioncrawler = 108,
        DogWild = 109,
        DogWar = 110,
        Doppleganger = 111,
        DopplegangerGreater = 112,
        Drizzt = 113,
        Elminster = 114,
        Ettercap = 115,
        Ghoul = 116,
        GhoulReveant = 117,
        GhoulGhast = 118,
        Gibberling = 119,
        Gnoll = 120,
        Hobgoblin = 121,
        Kobold = 122,
        KoboldTasloi = 123,
        KoboldXvart = 124,
        Ogre = 125,
        OgreMage = 126,
        OgreHalfogre = 127,
        OgreOgrillon = 128,
        Sarevok = 129,
        FairySirine = 130,
        FairyDryad = 131,
        FairyNereid = 132,
        FairyNymph = 133,
        Skeleton = 134,
        SkeletonWarrior = 135,
        SkeletonBaneguard = 136,
        SpiderGiant = 137,
        SpiderHuge = 138,
        SpiderPhase = 139,
        SpiderSword = 140,
        SpiderWraith = 141,
        Volo = 142,
        Wolf = 143,
        WolfWorg = 144,
        WolfDire = 145,
        WolfWinter = 146,
        WolfVampiric = 147,
        WolfDread = 148,
        Wyvern = 149,
        OliveSlime = 150,
        MustardJelly = 151,
        OcreJelly = 152,
        GreyOoze = 153,
        GreenSlime = 154,
        Innocent = 155,
        FlamingFist = 156,
        Werewolf = 157,
        Wolfwere = 158,
        Deathknight = 159,
        Tanari = 160,
        Beholder = 161,
        MindFlayer = 162,
        Vampire = 163,
        Vampyre = 164,
        Otyugh = 165,
        Rakshasa = 166,
        Troll = 167,
        Umberhulk = 168,
        Sahuagin = 169,
        Shadow = 170,
        Spectre = 171,
        Wraith = 172,
        KuoToa = 173,
        Mist = 174,
        Cat = 175,
        Duergar = 176,
        Mephit = 177,
        Mimic = 178,
        Imp = 179,
        Giant = 180,
        Orc = 181,
        GolemIron = 182,
        GolemFlesh = 183,
        GolemStone = 184,
        GolemClay = 185,
        ElementalAir = 186,
        ElementalFire = 187,
        ElementalEarth = 188,
        SpiderCenteol = 189,
        RedDragon = 190,
        ShadowDragon = 191,
        SilverDragon = 192,
        GenieDjinni = 193,
        GenieDao = 194,
        GenieEfreeti = 195,
        GenieNobleDjinni = 196,
        GenieNobleEfreeti = 197,
        ZombieNormal = 198,
        FoodCreature = 199,
        HunterCreature = 200,
        LongSword = 201,
        MageAll = 202,
        FighterAll = 203,
        ClericAll = 204,
        ThiefAll = 205,
        BardAll = 206,
        PaladinAll = 207,
        DruidAll = 208,
        RangerAll = 209,
        WizardEye = 210,
        CandlekeepWatcher = 211,
        AmnishSoldier = 212,
        TownGuard = 213,
        ElementalWater = 219,
        GreenDragon = 220,
        SodTmp = 221,
        SpectralTroll = 222,
        Wight = 223,
        NoClass = 255,
    }
}

impl Class {
    pub fn class_count(&self) -> u8 {
        match self {
            Class::FighterMage
            | Class::FighterCleric
            | Class::FighterThief
            | Class::MageThief
            | Class::ClericMage
            | Class::ClericThief
            | Class::FighterDruid
            | Class::ClericRanger => 2,

            Class::FighterMageCleric | Class::FighterMageThief => 3,

            Class::NoClass => 0,

            _ => 1,
        }
    }
}
