[package]
name = "bg-radar-linux-core"
version.workspace = true
edition.workspace = true

[dependencies]
encoding_rs = "0.8.35"
libc.workspace = true
regex = "1.11.1"
rust-utils.workspace = true
static_assertions = "1.1.0"

[dev-dependencies]
zstd = "0.13.3"
tar = "0.4.44"
